/*
 * config.h
 * All Peripheral and pin's defined in one file.
 * See: Assignment Specifications
 *
 * Authors: Liam Diprose, Aden Durney
 */

#ifndef CONFIG_H_
#define CONFIG_H_

// Increase Altitude Button
#define BUTTON_ALT_UP_PERIPH SYSCTL_PERIPH_GPIOE
#define BUTTON_ALT_UP_BASE GPIO_PORTE_BASE
#define BUTTON_ALT_UP_PIN GPIO_PIN_0

// Decrease Altitude Button
#define BUTTON_ALT_DOWN_PERIPH SYSCTL_PERIPH_GPIOD
#define BUTTON_ALT_DOWN_BASE GPIO_PORTD_BASE
#define BUTTON_ALT_DOWN_PIN GPIO_PIN_2

// Rotate Clockwise Button
#define BUTTON_YAW_LEFT_PERIPH SYSCTL_PERIPH_GPIOF
#define BUTTON_YAW_LEFT_BASE GPIO_PORTF_BASE
#define BUTTON_YAW_LEFT_PIN GPIO_PIN_0

// Rotate Counter-clockwise Button
#define BUTTON_YAW_RIGHT_PERIPH SYSCTL_PERIPH_GPIOF
#define BUTTON_YAW_RIGHT_BASE GPIO_PORTF_BASE
#define BUTTON_YAW_RIGHT_PIN GPIO_PIN_4

// Reset Button
#define BUTTON_RESET_PERIPH SYSCTL_PERIPH_GPIOA
#define BUTTON_RESET_BASE GPIO_PORTA_BASE
#define BUTTON_RESET_PIN GPIO_PIN_6

// Flight Mode Switch
#define SWITCH_FMODE_PERIPH SYSCTL_PERIPH_GPIOA
#define SWITCH_FMODE_BASE GPIO_PORTA_BASE
#define SWITCH_FMODE_PIN GPIO_PIN_7

// Main Roter PWM Output
#define PWM_ALT_PWM_PERIPH SYSCTL_PERIPH_PWM0
#define PWM_ALT_PWM_BASE PWM0_BASE
#define PWM_ALT_GEN PWM_GEN_3
#define PWM_ALT_OUT PWM_OUT_7
#define PWM_ALT_OUTBIT PWM_OUT_7_BIT
#define PWM_ALT_GPIO_PERIPH SYSCTL_PERIPH_GPIOC
#define PWM_ALT_GPIO_BASE GPIO_PORTC_BASE
#define PWM_ALT_GPIO_PIN GPIO_PIN_5
#define PWM_ALT_GPIO_PIN_CONF GPIO_PC5_M0PWM7

// Tail Rotor PWM Output
#define PWM_YAW_PWM_PERIPH SYSCTL_PERIPH_PWM1
#define PWM_YAW_PWM_BASE PWM1_BASE
#define PWM_YAW_GEN PWM_GEN_2
#define PWM_YAW_OUT PWM_OUT_5
#define PWM_YAW_OUTBIT PWM_OUT_5_BIT
#define PWM_YAW_GPIO_PERIPH SYSCTL_PERIPH_GPIOF
#define PWM_YAW_GPIO_BASE GPIO_PORTF_BASE
#define PWM_YAW_GPIO_PIN GPIO_PIN_1
#define PWM_YAW_GPIO_PIN_CONF GPIO_PF1_M1PWM5

#endif /* CONFIG_H_ */
